; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[adafruit_feather_m4]
platform = atmelsam
board = adafruit_feather_m4
framework = arduino
upload_protocol = sam-ba
board_upload.use_1200bps_touch = false
board_upload.wait_for_upload_port = false
extra_scripts = pre:wait_for_bootloader.py
monitor_speed = 115200
build_src_filter =
	-<.git/>
	-<.svn/>
	+<*.h>
	+<${PIOENV}.cpp>


[midi_build_flags]
build_flags =
	-DUSE_TINYUSB
	-DCFG_TUH_ENABLED=1
	-DCFG_TUH_MIDI=1
	-DCFG_TUH_ENUMERATION_BUFSIZE=256
	-I${sysenv.HOME}/.platformio/packages/framework-arduino-samd-adafruit/libraries/SPI

[lib_deps]
; lib_deps = 
; 	bolderflight/Bolder Flight Systems SBUS@^8.1.4

[env:blinky]
extends = lib_deps, adafruit_feather_m4

[env:midi_device_test]
extends = lib_deps, adafruit_feather_m4
lib_deps =
	adafruit/Adafruit TinyUSB Library@^3.3.4
	fortyseveneffects/MIDI Library@^5.0.2

[env:midi_test_v01]
extends = adafruit_feather_m4
lib_deps =
	adafruit/Adafruit TinyUSB Library
	fortyseveneffects/MIDI Library@^5.0.2
build_flags =
	-DUSE_TINYUSB
	-DCFG_TUH_ENABLED=1
	-DCFG_TUH_MIDI=1
	-DCFG_TUH_ENUMERATION_BUFSIZE=256
	-I${sysenv.HOME}/.platformio/packages/framework-arduino-samd-adafruit/libraries/SPI


[env:midi_test_v02_cc_in_to_DAC_out]
extends = adafruit_feather_m4, midi_build_flags
lib_deps =
	adafruit/Adafruit TinyUSB Library
	fortyseveneffects/MIDI Library@^5.0.2
; build_flags =
; 	-DUSE_TINYUSB
; 	-DCFG_TUH_ENABLED=1
; 	-DCFG_TUH_MIDI=1
; 	-DCFG_TUH_ENUMERATION_BUFSIZE=256
; 	-I${sysenv.HOME}/.platformio/packages/framework-arduino-samd-adafruit/libraries/SPI

[env:midi_test_v03_ledCC_to_dac1_noods_protocol]
extends = adafruit_feather_m4, midi_build_flags
lib_deps =
	adafruit/Adafruit TinyUSB Library
	fortyseveneffects/MIDI Library@^5.0.2
	khoih-prog/FlashStorage_SAMD
; build_flags =
; 	-DUSE_TINYUSB
; 	-DCFG_TUH_ENABLED=1
; 	-DCFG_TUH_MIDI=1
; 	-DCFG_TUH_ENUMERATION_BUFSIZE=256
; 	-I${sysenv.HOME}/.platformio/packages/framework-arduino-samd-adafruit/libraries/SPI

[env:midi_host_test]
extends = adafruit_feather_m4
lib_deps =
	adafruit/Adafruit TinyUSB Library
build_flags =
	-DUSE_TINYUSB
	-DCFG_TUH_ENABLED=1
	-DCFG_TUH_MIDI=1
	-DCFG_TUH_ENUMERATION_BUFSIZE=256
	-I${sysenv.HOME}/.platformio/packages/framework-arduino-samd-adafruit/libraries/SPI
